### ISSUE TITLE
Replace usage of asserts with ValueError checks

### ISSUE THREAD

**Issue by vdusek** [apify/apify-sdk-python#137]
Replace usage of asserts with ValueError checks as violation [S101](https://docs.astral.sh/ruff/rules/assert/) suggests.

Motivation in the link.

**Comment by fnesveda** [comment]
Good point, especially in https://github.com/apify/apify-sdk-python/blob/master/src/apify/proxy_configuration.py#L280-L282 or in the storages code it's used wrongly. But in a lot of places we use assert just as a type assertion to fool Mypy, maybe we can keep it there? Unless then the S101 rule would be too difficult to set up, in that case let's just switch to `ValueError`s everywhere.

**Comment by vdusek** [comment]
> But in a lot of places we use assert just as a type assertion to fool Mypy, maybe we can keep it there?

I got it, however, I suppose the use of `isinstance()` should have the same effect, don't you think?
