### ISSUE TITLE
Replace the usage of `Any` with generic types

### ISSUE THREAD

**Issue by vdusek** [apify/apify-sdk-python#138]
Do not use `Any` type as suggested in the [ANN401](https://docs.astral.sh/ruff/rules/any-type/).

Instead of
```python
from typing import Any

def get_first(container: list[Any]) -> Any:
    return container[0]
```

use the following
```python
from typing import TypeVar

T = TypeVar('T')

def get_first(container: list[T]) -> T:
    return container[0]
```

`Any` can probably still make sense for the `*args` / `**kwargs`.

**Comment by janbuchar** [comment]
After #210, I believe the only notable offender is the input shape in `Actor`.
