### ISSUE TITLE
Correctly handle actor exit

### ISSUE THREAD

**Issue by janbuchar** [apify/apify-sdk-python#200]
Originally reported in https://apify.slack.com/archives/CGZSN9DQC/p1715957828029029.

The user spawned an asyncio task in the actor. When the actor finished (reached the end of the `Actor` context manager block), it didn't clean up the task and the container was left there hanging.

We should either cancel all tasks when the actor is exitting or just trigger a `sys.exit` after a certain timeout.

[Relevant code](https://github.com/apify/apify-sdk-python/blob/master/src/apify/actor.py) and [JS counterpart](https://github.com/apify/apify-sdk-js/blob/master/packages/apify/src/actor.ts)

**Comment by B4nan** [comment]
we should put priority on this one, at least implement the configurable timeout after which we kill the process completely, we can leave the wait for bound events (via `actor.on`) for later if it would be too time consuming.
