### ISSUE TITLE
SDK 2 finalization

### ISSUE THREAD

**Issue by B4nan** [apify/apify-sdk-python#262]
- [x] `availableMemoryRatio` not used at all, should be used in snapshotter
	- https://github.com/apify/crawlee-python/pull/502
- [x] `memoryMbytes` not used at all, should be used in snapshotter 
	- https://github.com/apify/crawlee-python/pull/502
- [x] separate apify deployment guide as in https://crawlee.dev/docs/deployment/apify-platform 
	- https://github.com/apify/crawlee-python/pull/482
- [x] apify client batch add requests not handled properly (API allows only 25 items in one call)
	- https://github.com/apify/apify-client-python/issues/264
	- https://github.com/apify/apify-sdk-python/pull/261
- [x] actor templates with crawlee for python
- [x] logging configuration in SDK
- [ ] more python playwright images (later)

**Comment by Abhijit-Guragain** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by B4nan** [comment]
also maybe the `disableBrowserSandbox` flag which adds `--no-sandbox` to chrome launch args, which was needed for playwright on platform IIRC

**Comment by janbuchar** [comment]
> also maybe the `disableBrowserSandbox` flag which adds `--no-sandbox` to chrome launch args, which was needed for playwright on platform IIRC

This might be worth digging into - I couldn't find any documentation of the variable. I'm pretty sure playwright works just fine on platform without that.

**Comment by B4nan** [comment]
Maybe, I just tried to find when we added it and it is really ancient, here is a commit that apparently reverts its removal:

https://github.com/apify/apify-ts/commit/c4a44af198fdc5373154bbf5eb2182593ea9de87

Also some relevant SO post:

https://stackoverflow.com/questions/50662388/running-headless-chrome-puppeteer-with-no-sandbox

Maybe it's not relevant anymore, and maybe its just about chrome and not chromium (looking at our python playwright docker image, we don't use chrome in there, right?)

**Comment by janbuchar** [comment]
> Maybe it's not relevant anymore, and maybe its just about chrome and not chromium (looking at our python playwright docker image, we don't use chrome in there, right?)

Yeah, looks like we only allow chromium, on the type level. If you install chrome and ignore the type error, it will probably work though.

**Comment by B4nan** [comment]
we'll need to try it, should be enough to run pw+chrome with js version with `disableBrowserSandbox: false` on platform, same for puppeteer i guess, but i can imagine both will behave the same. i would also try both headless/headful modes.

**Comment by vdusek** [comment]
Seems to be ready, closing, and releasing 2.0.
