### ISSUE TITLE
Handle request list and proxy configuration inputs in a user-friendly way

### ISSUE THREAD

**Issue by janbuchar** [apify/apify-sdk-python#310]
- https://docs.apify.com/platform/actors/development/actor-definition/input-schema/specification/v1#array - request list editor
- https://docs.apify.com/platform/actors/development/actor-definition/input-schema/specification/v1#object - proxy editor

An `actor.json` like this:

```json
{
    "actorSpecification": 1,
    "name": "example-actor",
    "version": "0.0",
    "buildTag": "latest",
    "environmentVariables": {},
    "input": {
        "properties": {
            "startUrls": {
                "title": "Start URLs",
                "type": "array",
                "description": "URLs to start with",
                "prefill": [
                    {
                        "url": "https://apify.com"
                    }
                ],
                "editor": "requestListSources"
            },
            "proxyConfiguration": {
                "title": "Proxy configuration",
                "type": "object",
                "description": "Select proxies to be used by your crawler.",
                "prefill": {
                    "useApifyProxy": true
                },
                "editor": "proxy"
            }
        }
    }
}

```

will have an input editor like this:

![image](https://github.com/user-attachments/assets/d9daff56-f8f2-4b80-948e-3beeb821374c)

and calling `Actor.get_input()` in the actor will result into something like this:

```py
{
    "proxyConfiguration": {
        "useApifyProxy": True,
        "apifyProxyGroups": ["BUYPROXIES63811", "SHADER"],
    },
    "startUrls": [
        {"url": "https://google.com", "method": "GET"},
        {"url": "https://salas.hu", "method": "GET"},
        {"url": "https://trivago.hu", "method": "GET"},
        {"requestsFromUrl": "https://lorem.se/ipsum.txt", "method": "GET"},
    ],
}
```

It would be awesome if we could implement some helpers to simplify converting these structures into `crawlee.storage.RequestList` or `apify.ProxyConfiguration`. 

Since it is pretty convenient to have the input structure described with a Pydantic model (so you can do `Input.model_validate(await Actor.get_input())`, I would love to explore the possibility of adding some Pydantic models that you could use in your `Input` models and then pass them to `ProxyConfiguration` or `RequestList` constructors (or some factory methods).

**Comment by Pijukatel** [comment]
Pydantic seems natural for handling inputs, on the other hand it seems like it was already intentionally removed: https://github.com/apify/apify-sdk-python/pull/74

I do not have enough historical context. Is the reasoning behind not using Pydantic here still valid?

**Comment by vdusek** [comment]
> Pydantic seems natural for handling inputs, on the other hand it seems like it was already intentionally removed: https://github.com/apify/apify-sdk-python/pull/74
>
> I do not have enough historical context. Is the reasoning behind not using Pydantic here still valid?

We put it back. Pydantic is now used in many places throughout Crawlee, and so in the SDK as well. See https://github.com/apify/apify-sdk-python/issues/64#issuecomment-1970827823 for more details.
