### ISSUE TITLE
Missing classes in docs

### ISSUE THREAD

**Issue by TC-MO** [apify/apify-sdk-python#314]
While checking out Lychee Link Checker report I noticed that Python SDK is missing classes in docs.

seems like Dataset,KeyValueStore & RequestQueue are missing maybe others too

**Comment by vdusek** [comment]
You mean in the [API docs](https://docs.apify.com/sdk/python/reference), correct? The storage classes live in the Crawlee repository now. We are just re-exporting them here... It seems like more work for @barjin. We should either link these storage classes from SDK or take the docstring content from Crawlee and render them in the SDK as well. Both approaches work fine for me. cc @janbuchar

**Comment by janbuchar** [comment]
@TC-MO I believe this is resolved now - can you please confirm that?

**Comment by TC-MO** [comment]
Indeed it looks like it, we are all green on Lychee, much obliged!
