### ISSUE TITLE
Forefront parameter for request queue client in MemoryStorage does not work

### ISSUE THREAD

**Issue by jirimoravcik** [apify/apify-sdk-python#66]
See https://github.com/apify/crawlee/issues/1787

We currently ignore the `orderNo` property in `list_head`.

TODO:
1. Fix methods to respect the `forefront` parameter
2. Add it to unit tests

**Comment by fnesveda** [comment]
Maybe it would be enough to sort the items by orderno. Or have the request in a sorted list already from insertion.
