### ISSUE TITLE
We should mention how to install the SDK (`pip install apify`) somewhere in the docs

### ISSUE THREAD

**Issue by jbartadev** [apify/apify-sdk-python#89]
On the docs page for Apify Python SDK, there is never mention of how to actually install the SDK (pip install apify), not even in the GitHub repo or Getting Started page.

@fnesveda says: 
That was kinda intentional, because we wanted to lead people to create actors with Apify CLI or on the platform, and it's a bit confusing that you would pip install apify but then apify create would not work (because you need the CLI installed).
But I agree that we should probably at least mention it somewhere.

**Comment by fnesveda** [comment]
Fixed in 76b5dbc84bb7d7c00c2f5c1cbfe870cbbf48cb29
