### ISSUE TITLE
Actor.reboot() doesn't work

### ISSUE THREAD

**Issue by ramicaza** [apify/apify-sdk-python#94]
Actor.reboot() fails because it doesn't pass in the old Actor's input to the new one. Thus, if the actor requires any input, it fails and puts the original actor in a weird state.

The workaround is to do this:
a = Actor._get_default_instance()
await Actor.metamorph(a._config.actor_id, actor_input)

But this isn't ideal, so please either pass the old input to the new actor or have a parameter in reboot() in which we can pass the input.

**Comment by jirimoravcik** [comment]
Hello @ramicaza,

I would like to thank you for reporting this bug.
We'll look into the problem as soon as possible.

Cheers,
Jiri

**Comment by B4nan** [comment]
@jirimoravcik is this something @vdusek can help with?

**Comment by jirimoravcik** [comment]
> @jirimoravcik is this something @vdusek can help with?

Hey, currently, I'm adding a new API endpoint for the reboot. When this is done, we'll need to add a call to that endpoint to both our clients and then propagate them to SDKs. I think that would be a great task for @vdusek 

I'll ping you when I finish the platform side and we'll discuss how to proceed from there!

**Comment by vdusek** [comment]
Closing the issue since the `Actor.reboot` method was fixed in the https://github.com/apify/apify-sdk-python/issues/101 and a new version of the SDK was release - https://pypi.org/project/apify/1.1.3/.
