### ISSUE TITLE
Use ACTOR_XXX env vars which was replaced some APIFY_ACTOR_XXX

### ISSUE THREAD

**Issue by jirimoravcik** [apify/apify-sdk-python#95]
Use some of ACTOR_XXX env vars instead of APIFY_ACTOR_XXX

See the list in [actor spec](https://github.com/apify/actor-specs/#environment-variables)

It would be cool do to this along with creation of `apify-shared-python`, since the env vars are currently defined in `consts.py` file in this repo...

**Comment by fnesveda** [comment]
@jirimoravcik Unless you have already started with this, it can wait a bit, @vdusek is working on creating `apify-shared-python` right now, so we can add it there once we have it. It will be a good opportunity to test the CI there too.

**Comment by jirimoravcik** [comment]
> @jirimoravcik Unless you have already started with this, it can wait a bit, @vdusek is working on creating `apify-shared-python` right now, so we can add it there once we have it. It will be a good opportunity to test the CI there too.

Yeah, I did not do this since I was waiting for the `apify-shared-python`
